name: Release

on:
  push:
    branches:
      - develop
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  # build:
  #   name: Release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js 24
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 24

  #     - name: Install Dependencies
  #       run: npm ci

  #     - name: Build
  #       run: npm run build

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm ci

      

      - name: Enter Pre-release Mode (dev)
        if: github.ref == 'refs/heads/develop'
        run: |
          if [ ! -f .changeset/pre.json ]; then
            npx changeset pre enter dev
          else
            echo "Already in pre mode, skipping changeset pre enter dev"
          fi

      - name: Create Release Pull Request
        id: create_release_pr
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Exit Pre-release Mode in changeset/release-main
        if: github.ref == 'refs/heads/main' 
        # && steps.create_release_pr.outputs.hasChangesets == 'true'
        run: |
          if [ -f .changeset/pre.json ]; then
          
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            
            git checkout -b changeset-release/main origin/changeset-release/main

            npx changeset pre exit

            git add .
            git commit -m "Exiting pre-release mode" || echo "No changes to commit" >> $GITHUB_STEP_SUMMARY

            git push origin changeset/release-main
          else
            echo "Not in pre mode, skipping changeset pre exit"
          fi