name: Release

on:
  push:
    branches:
      - develop
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  # build:
  #   name: Release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js 24
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 24

  #     - name: Install Dependencies
  #       run: npm ci

  #     - name: Build
  #       run: npm run build

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Enter Pre-release Mode (dev)
        if: github.ref == 'refs/heads/develop'
        run: |
          if [ ! -f .changeset/pre.json ]; then
            npx changeset pre enter dev
          else
            echo "Already in pre mode, skipping changeset pre enter dev"
          fi

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}